"""add is_deleted column to shows for soft delete

Revision ID: 4961f7d5be89
Revises: dfe06ffeb0c2
Create Date: 2025-05-20 23:24:14.853975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4961f7d5be89'
down_revision: Union[str, None] = 'dfe06ffeb0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show_seat_history', 'timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('show_seat_history', 'seats',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_show_seat_history_timestamp'), 'show_seat_history', ['timestamp'], unique=False)
    op.add_column('shows', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'is_deleted')
    op.drop_index(op.f('ix_show_seat_history_timestamp'), table_name='show_seat_history')
    op.alter_column('show_seat_history', 'seats',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('show_seat_history', 'timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
