"""empty message

Revision ID: 9598994bf033
Revises: b890ff1a5b99
Create Date: 2024-12-29 21:41:30.296496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9598994bf033'
down_revision: Union[str, None] = 'b890ff1a5b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('previous_seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'previous_seats')
    # ### end Alembic commands ###
