"""Init

Revision ID: e00f3228618e
Revises:
Create Date: 2024-02-11 19:56:16.362692
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e00f3228618e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column(
            'user_id', sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('bot_full_name', sa.String(), nullable=True),
        sa.Column('spectacle_full_name', sa.String(), nullable=True),
        sa.Column('search_count', sa.Integer(), nullable=True),
        sa.Column('actor', sa.Boolean(), nullable=True),
        sa.Column('assistant_director', sa.Boolean(), nullable=True),
        sa.Column('administrator', sa.Boolean(), nullable=True),
        sa.Column('throttling', sa.Integer(), nullable=True),
        sa.Column('banned', sa.Boolean(), nullable=True),
        sa.Column('admin', sa.Boolean(), nullable=True),
        sa.Column(
            'start_bot_date',
            sa.Integer(),
            server_default=sa.text('EXTRACT(epoch FROM now())'),
            nullable=True,
        ),
        sa.Column('bot_blocked', sa.Boolean(), nullable=True),
        sa.Column('bot_blocked_date', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('user_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
