https_port 3129 tls-cert=/run/secrets/proxy.crt tls-key=/run/secrets/proxy.key
auth_param basic program /usr/lib/squid/basic_ncsa_auth /run/secrets/passwords
auth_param basic realm Mosbilet
acl authenticated proxy_auth REQUIRED
acl bot_server src "/run/secrets/allowed-clients"
acl CONNECT method CONNECT
acl tls_port port 443
acl mosbilet dstdomain tickets.mos.ru
http_access deny !bot_server
http_access deny !CONNECT
http_access deny !tls_port
http_access deny !mosbilet
http_access allow authenticated
http_access deny all
cache deny all
pinger_enable off
access_log none
cache_log /dev/stderr
pid_filename /tmp/squid.pid
netdb_filename none
visible_hostname mosbilet-proxy
shutdown_lifetime 1 seconds
